### ISSUE TITLE
The app won't start on MacOS

### ISSUE THREAD

**Issue by lukigarazus** [localstack/localstack-desktop#1]
<img width="239" alt="Screenshot 2023-11-12 at 19 21 18" src="https://github.com/localstack/localstack-desktop/assets/32484818/1195c7f5-9a94-4ed7-97d8-74b80f36c0d0">

**Comment by lukqw** [comment]
Hi there @lukigarazus!
Thanks a lot for raising this issue - we are delighted to inform you that we should have resolved the issue.

Could you please download the app again and see whether the issue still persists?

**Comment by Pive01** [comment]
Closing as the Issue seems to be resolved on our side. If the problem persist feel free to re-open it
