### ISSUE TITLE
More errors

### ISSUE THREAD

**Issue by olfek** [localstack/localstack-desktop#11]
LocalStack Desktop version - `1.0.4 (community)`
Docker version - `26.0.0, build 2ae903e`

```
     Edition  Windows 11 Pro
     Version  23H2
    OS build  22631.3447
  Experience  Windows Feature Experience Pack 1000.22688.1000.0
```

![image](https://github.com/localstack/localstack-desktop/assets/27283110/b1013192-7c1e-4dae-9128-9d729777d75b)
![image](https://github.com/localstack/localstack-desktop/assets/27283110/51dbb1c5-7dc2-40a7-8982-b0125dc54e64)
![image](https://github.com/localstack/localstack-desktop/assets/27283110/b8abeda9-9c86-4570-b786-042041def7dd)
![image](https://github.com/localstack/localstack-desktop/assets/27283110/2f02e396-9ec0-460d-80f9-95d28a62e3d0)
![image](https://github.com/localstack/localstack-desktop/assets/27283110/4702c46b-161f-4b03-b18e-d8bf2e8ddeef)

**Comment by Pive01** [comment]
Hello @olfek , thanks for your submission. We found the issue and it will be fixed with the next release :muscle:
