### ISSUE TITLE
Changing the socket doesn't work immediately

### ISSUE THREAD

**Issue by Varstahl** [localstack/localstack-desktop#12]
I was trying to make the desktop app working, without much success. After a *lot* of fiddling I realized that after you save the socket path, it's not actually taken into consideration until you restart the whole application, but that's not even mentioned in the app itself.

I've only noticed the behaviour after a change, where the app was still trying to repeatedly connect to the previous one.

It also works in reverse, where if I put an invalid one from the valid one, it still shows the stacks instead of erroring out.

The app needs to flush all results on a socket change and retry on the newly supplied socket.

**Comment by Pive01** [comment]
Hi @Varstahl  thanks for submitting your issue. If you look at the description it actually says that you need to restart for it to take effect. We'll try to provide a better UX nevertheless 

![image](https://github.com/localstack/localstack-desktop/assets/36865043/5445dede-a823-4c61-b826-b08f75798ea3)
