### ISSUE TITLE
Windows preset

### ISSUE THREAD

**Issue by Varstahl** [localstack/localstack-desktop#13]
LocalStack Desktop for Windows should come up preset with the default `//./pipe/docker_engine`, especially when provided through MS Store.

This, combined with #12, caused a lot of unnecessary friction.

**Comment by Pive01** [comment]
HI @Varstahl  thanks for submitting your issue. You raised a good observation and we will provide pre-filled values based on OS  for next release

**Comment by Pive01** [comment]
Closing as it is solved with latest release (1.0.6)
