### ISSUE TITLE
Localstack Desktop - Windows

### ISSUE THREAD

**Issue by renerlemes** [localstack/localstack-desktop#14]
I downloaded the application for Windows using the URL https://app.localstack.cloud/download, which is redirected to the Windows store, but when I click on download and have the EXE and click to install, nothing happens and no is installed.

![image](https://github.com/localstack/localstack-desktop/assets/2191533/aa0b0306-1b3c-4212-aaba-85a9a00fadde)

If I try from the store, an error message occurs

![image](https://github.com/localstack/localstack-desktop/assets/2191533/24834da9-2d28-4642-91b6-4902f3de32a3)

Is there any other way to download and install it?

**Comment by Pive01** [comment]
Hi @renerlemes, thanks for submitting your issue. It appears that recently the Microsoft store lets you download a .exe which is news to me :sweat_smile: . If you go back to the Microsoft store from the link of the web app you should see also a "View in store" button... If you try that and let the Microsoft store handle the installation part does it work for you or still gives you issues?


![image (4)](https://github.com/localstack/localstack-desktop/assets/36865043/a530a0f5-eaa0-4647-aee1-bbf2062120db)

**Comment by renerlemes** [comment]
@Pive01 I discovered the problem. Using the work computer, the store is blocked and therefore cannot install (not even with the .exe, as it is a store installer). On another computer it is possible.

I downloaded it to my personal computer, installed it, copied the installation files to the other computer and was able to run it.

Is there any other way to get the installer outside the store?

**Comment by Pive01** [comment]
Hi @renerlemes , glad you figured it out; At the moment there is no way to get the desktop app outside of the windows store (on windows); will ping you here again in case we decide to provide an additional download method.
For now I'll close the issue :+1:

**Comment by awongCM** [comment]
Hi @Pive01 
I'm running into this situation myself at my work.  I'm working for a large corporate company and present our company IT policies barred us from logging into IT store to download it.  Can you please an alternative approach to download the windows version? I have a few teammates that using windows machine that would be interested in getting this tool for their local development needs.
Thanks. 

> Hi [@renerlemes](https://github.com/renerlemes) , glad you figured it out; At the moment there is no way to get the desktop app outside of the windows store (on windows); will ping you here again in case we decide to provide an additional download method. For now I'll close the issue 👍

**Comment by Pive01** [comment]
Hi @awongCM , as mentioned above we do not distribute any alternative approaches for windows at the moment.
If you are interested in using the UI to interact with your instance we also offer our web application https://app.localstack.cloud/inst/default/resources 
If you seek further requirements for your company will invite you to reach out to our sales team at https://www.localstack.cloud/demo
