### ISSUE TITLE
Cannot login to access the Resource Browser

### ISSUE THREAD

**Issue by anudeepreddy** [localstack/localstack-desktop#2]
I have been trying to access the resource browser but I am unable to login. When a login is attempted it keeps loading and please look at the screenshot below. The request to https://api.localstack.cloud/v1/auth/request resulted in a gateway timeout.
![image](https://github.com/localstack/localstack-desktop/assets/6022231/4a88d4f9-56c2-44a8-af50-8f3da1383f9f)

**Comment by SimonWallner** [comment]
We experienced a brief service interruption around the time you reported this. Could you try it again and see if it works as expected now?
