### ISSUE TITLE
Multiple LocalStack Containers started from command line result in Unknown Endpoints in Container Viewer

### ISSUE THREAD

**Issue by Conzar** [localstack/localstack-desktop#3]
## Problem
Starting containers via the command line per the [External-Ports](https://docs.localstack.cloud/references/external-ports/) documentation causes the LocalStack Container Viewer in the Desktop Application to not find the Endpoint for containers started on ports other than 4566.

## Example
The following code starts 2 containers: environment1 & system.

```bash
GATEWAY_LISTEN=0.0.0.0:4566 EXTERNAL_SERVICE_PORTS_START=4510 EXTERNAL_SERVICE_PORTS_END=4559 MAIN_CONTAINER_NAME=localstack-environment1 localstack start &
GATEWAY_LISTEN=0.0.0.0:4666 EXTERNAL_SERVICE_PORTS_START=4610 EXTERNAL_SERVICE_PORTS_END=4659 MAIN_CONTAINER_NAME=localstack-system localstack start &
```

The LocalStack Desktop Application Container Viewer Detects that both containers exist but can only connect to environment1 using the default 4566 endpoint port.

![image](https://github.com/localstack/localstack-desktop/assets/2646975/46180a01-b418-467e-a912-0ed51e5699d9)

## Work Around
A new endpoint can be added for containers not on 4566.  However, this will duplicate the number of entries in the Container Viewer as there will be 1 entry with the endpoint issue and one entry that can only view.

## Desired Functionality

The LocalStack Desktop Application automatically picks up local containers on non-standard ports.

## Possible Solutions
(I haven't looked at the code)
* Run a docker command on each LocalStack container that returns the endpoint using the output (most efficient method but will require a change to the docker container)
* The LocalStack Desktop application poll ports searching for an endpoint on the container (not efficient but doesn't require any changes to the docker container).

**Comment by Pive01** [comment]
Closing this issue as it should be resolve with the latest version since we've introduced the auto-discovery of the port
