### ISSUE TITLE
Getting an XML error when creating a S3 bucket without adding a region.

### ISSUE THREAD

**Issue by kaisbushby** [localstack/localstack-desktop#4]
When creating an S3 bucket without adding a Region the application sends an error "The XML you provided was not well-formed or did not validate against our published schema".
This error doesn't occur with the web portal version of localstack.

Upon further inspection the desktop version seems include a body in the PUT request, which adds a _LocationContraint_ XML tag with no value inside regardless if a Region is selected or not.

<img width="718" alt="localstack-s3-error" src="https://github.com/localstack/localstack-desktop/assets/45066599/e8ff6163-4784-4694-badd-88b1258195c3">

[localstack-desktop-create-s3.txt](https://github.com/localstack/localstack-desktop/files/13595362/localstack-desktop-create-s3.txt)

**Comment by Pive01** [comment]
Hello @kaisbushby , thank you for your submission! We are aware of the problem and will release a new version with the fix soon!

**Comment by Pive01** [comment]
Hello @kaisbushby, the new version (1.0.2) should've fixed the problem. If the issue persist feel free to re-open the issue
