### ISSUE TITLE
Error "Cannot read properties of undefined (reading 'filter')"

### ISSUE THREAD

**Issue by olfek** [localstack/localstack-desktop#6]
<img width=600 src="https://github.com/localstack/localstack-desktop/assets/27283110/1c081e63-fa31-4eb7-a1f8-b3f499636765" />

```
LocalStack Desktop: 1.0.3
           Edition: Windows 11 Pro
           Version: 23H2
          OS build: 22631.3235
        Experience: Windows Feature Experience
                    Pack 1000.22687.1000.0
```

**Comment by Pive01** [comment]
Hi @olfek  thanks for your report. We are going to release a fix for that in the next release; In the meantime, simply adding one Env Var should solve your issue.

**Comment by Pive01** [comment]
Closing this as it should be resolved with the latest release @olfek
