### ISSUE TITLE
The URL for the Microsoft Store is incorrect

### ISSUE THREAD

**Issue by baynezy** [localstack/localstack-desktop#7]
The URL for the store gives me an error.

**Comment by Pive01** [comment]
Thanks for the report @baynezy .
It works for me 🤔 , but is indeed slower to load compared to the other. Will take a closer look tomorrow 👍

**Comment by baynezy** [comment]
@Pive01 - that is interesting I got a `503` response yesterday. Maybe they were having an outage.
